# Generated by Django 3.0.4 on 2020-04-05 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_two', '0003_auto_20200403_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texts',
            name='screenshots',
        ),
    ]
